# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools
language: c

# Caching so the next build will be fast too
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# Dependencies
addons:
  apt:
    packages:
    - ghc-7.10.3
    sources:
    - hvr-ghc

before_install:
- |
  # Download and unpack the stack executable & setup Hackage mirror
  export PATH=:$HOME/.local/bin:$HOME/.cabal/bin:$PATH
  mkdir -p ~/.local/bin
  travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

  mkdir -p $HOME/.cabal
  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config

install: stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script: bash ./deploy.sh
